version: "3.7"

services: 
    apache:
        image: apache-php:1.0
        build: image-apache
        container_name: apache
        restart: always
        ports:
            - 80:80

    mariadb:
        image: mariadb-php:1.0
        build: image-mariadb
        container_name: mariadb
        restart: always
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
        ports:
            - 3306:3306
